#pragma once

#include "engine/EngineSystemsOrders.h"

struct UserSystemsOrders
{
	struct Init
	{
		BAKA_SYSTEMS_ORDER(SCENE_0);
		BAKA_SYSTEMS_ORDER(TEST_0);
		BAKA_SYSTEMS_ORDER(SCENE_1);
		BAKA_SYSTEMS_ORDER(TEST_1);
		BAKA_SYSTEMS_ORDERS_TYPES(SCENE_0, TEST_0, SCENE_1, TEST_1);
	};

	struct Update
	{
		BAKA_SYSTEMS_ORDER(SCENE_0);
		BAKA_SYSTEMS_ORDER(TEST_0);
		BAKA_SYSTEMS_ORDER(SCENE_1);
		BAKA_SYSTEMS_ORDER(TEST_1);
		BAKA_SYSTEMS_ORDERS_TYPES(SCENE_0, TEST_0, SCENE_1, TEST_1);
	};

	struct Destroy
	{
		BAKA_SYSTEMS_ORDER(SCENE_0);
		BAKA_SYSTEMS_ORDER(TEST_0);
		BAKA_SYSTEMS_ORDER(SCENE_1);
		BAKA_SYSTEMS_ORDER(TEST_1);
		BAKA_SYSTEMS_ORDERS_TYPES(SCENE_0, TEST_0, SCENE_1, TEST_1);
	};
};